name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
softdepend: [Vault]
commands:
  petstore:
    description: PetStore Command
    permission: petstore.command
    aliases: pet
    usage: /petstore <transfer | give | sell | release | tame | cancel>
permission:
  petstore.command:
    description: Allows access to the PetStore base command.
    default: true
  petstore.cancel:
    description: Allows access to the PetStore cancel command.
    default: true
  petstore.transfer:
    description: Allows access to the PetStore transfer command.
    default: true
    children:
      petstore.command: true
  petstore.give:
    description: Allows access to the PetStore give command.
    default: true
    children:
      petstore.command: true
      petstore.cancel: true
  petstore.sell:
    description: Allows access to the PetStore sell command.
    default: true
    children:
      petstore.command: true
      petstore.cancel: true
  petstore.release:
    description: Allows access to the PetStore release command.
    default: true
    children:
      petstore.command: true
  petstore.cancel:
    description: Allows access to the PetStore cancel command.
    default: true
    children:
      petstore.command: true
  petstore.tame:
    description: Allows access to the PetStore tame command.
    default: op
    children:
      petstore.command: true
  petstore.admin.notifyupdate:
    description: Notifies players when an update to PetStore is available.
    default: op