name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
softdepend: [Vault]
commands:
  petstore:
    description: PetStore Command
    permission: petstore.command
    aliases: pet
    usage: /petstore <transfer|give|sell>
permission:
  petstore.command:
    description: Allows access to the PetStore command.
    default: op