name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.author}
website: ${project.url}
main: ${project.main}
commands:
  ${project.name}:
    description: ${project.name} Command
    permission: ${project.name}.command
    aliases: pet
    usage: /${project.name} <transfer|give|sell>
permission:
  ${project.name}.command:
    description: Allows access to the ${project.name} command.
    default: op